icons_format = "{icon}"

[theme]
theme = "srcery"

[icons]
icons = "material-nf"

[[block]]
block = "net"
format = " $icon {$signal_strength$frequency $ssid|wired} ($device) "
missing_format = " \U000f0159  no connection "
#missing_format = " \uf00d no connection "

[[block]]
block = "external_ip"

[[block]]
block = "github"

[[block]]
block = "pacman"
#aur_command = "paru -Qu --dbpath /tmp/checkup-db-i3statusrs/"
aur_command = "paru -Qua"
format = " $icon $aur.eng(w:1) "
format_singular = " $icon $aur.eng(w:1) "
format_up_to_date = " $icon $aur.eng(w:1) "

[[block]]
block = "load"

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 60
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "
[block.icons_overrides]
disk_drive = "\uf1c0"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
[block.icons_overrides]
memory_mem = "\ue266"
#memory_mem = "\uf85a"
#memory_swap = "\ueb60"
memory_swap = "\uf15b"

[[block]]
block = "backlight"

[[block]]
block = "sound"
device_kind = "source"
[block.icons_overrides]
microphone = "\uf130"
microphone_muted = "\uf131"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = '/home/robert/bin/i3status-check-backup.sh'
json = true
interval = 30

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R')"

[[block]]
block = "battery"
[block.icons_overrides]
bat_not_available = "\U000f125e"
bat_charging = "\uf1e6"
bat = [
  "\uf244", # nf-fa-battery-0
	"\uf243", # nf-fa-battery-1
	"\uf242", # nf-fa-battery-2
	"\uf241", # nf-fa-battery-3
	"\uf240", # nf-fa-battery-4
]
